### ISSUE TITLE
Localhost only by default

### ISSUE THREAD

**Issue by cheesegrits** [transifex/txgh#17]
This isn't specifically a txgh issue, but something which ate a lot of time when I updated from my old fork to this one.  The new gem versions have changed the default behaviour of (I think) rack, so it now defaults to only listening to localhost.  The only way I found of changing that was a to set the environment variable RACK_ENV to 'production'.

I would update the README, but I'm not entirely sure if this is the correct way to handle it.  Also, it would be nice to not have to run in global 'production' mode, for instance if we used Logger, as even in development mode, we still need to listen on 0.0.0.0, but would want debug output.  So it would be nice to have a way of overriding the default listening IP, regardless of the run mode.

**Comment by matthewjackowski** [comment]
Agreed, I'm working on building some documentation per hosting provider that should help clarify.  Unfortunately I don't believe there is a good 'one size fits all' between AWS , Heroku and Docker.

**Comment by matthewjackowski** [comment]
Info on running on AWS is here: https://github.com/transifex/txgh/issues/14
