### ISSUE TITLE
 cannot load such file -- faraday_middleware

### ISSUE THREAD

**Issue by cheesegrits** [transifex/txgh#20]
I had to reboot my server, and now when trying to run txgh I get this:

/home/ec2-user/transifex/txgh/lib/strava/l10n/transifex_api.rb:2:in `require': cannot load such file -- faraday_middleware (LoadError)

I'm up to date with the devel branch.

I'm sure it's something to do with ruby's load paths, but I'm such a ruby noob I can't for the life of me work out how to fix it.  I had rather hoped bundler would sort it out, but apparently not.

   -- hugh

**Comment by matthewjackowski** [comment]
@cheesegrits 
My bad, it needs to be included separately now and I forgot to add it.  This commit should fix it for you: https://github.com/transifex/txgh/commit/78c1d36aeb5f0acc159ba5f901768ac4fdf9af3f

After you update the Gemfile ... just run bundle install and it should be added to your environment.

Matthew

**Comment by cheesegrits** [comment]
That did the trick.  Thanks.

   -- hugh
