### ISSUE TITLE
TypeError - can't convert nil into String

### ISSUE THREAD

**Issue by cheesegrits** [transifex/txgh#4]
Hey ...

Getting this error when github fires the webhook.  I know nothing about Ruby, or I'd have a go at tracking it down myself.  Really hoping I can get txgh going, as I badly need CI between a large github project and TF, so would appreciate any help I can get on this one.

TypeError - can't convert nil into String:
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/json-1.8.0/lib/json/common.rb:155:in `initialize'
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/json-1.8.0/lib/json/common.rb:155:in `new'
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/json-1.8.0/lib/json/common.rb:155:in `parse'
        /home/ec2-user/txgh/app/app.rb:61:in `block in <class:Hooks>'
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.3/lib/sinatra/base.rb:1541:in `call'
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.3/lib/sinatra/base.rb:1541:in `block in compile!'
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.3/lib/sinatra/base.rb:950:in `[]'
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.3/lib/sinatra/base.rb:950:in `block (3 levels) in route!'
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.3/lib/sinatra/base.rb:966:in `route_eval'
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.3/lib/sinatra/base.rb:950:in `block (2 levels) in route!'
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.3/lib/sinatra/base.rb:987:in `block in process_route'
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.3/lib/sinatra/base.rb:985:in `catch'
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.3/lib/sinatra/base.rb:985:in `process_route'
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.3/lib/sinatra/base.rb:948:in `block in route!'
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.3/lib/sinatra/base.rb:947:in `each'
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.3/lib/sinatra/base.rb:947:in `route!'
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.3/lib/sinatra/base.rb:1059:in `block in dispatch!'
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.3/lib/sinatra/base.rb:1041:in `block in invoke'
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.3/lib/sinatra/base.rb:1041:in `catch'
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.3/lib/sinatra/base.rb:1041:in `invoke'
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.3/lib/sinatra/base.rb:1056:in `dispatch!'
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.3/lib/sinatra/base.rb:882:in `block in call!'
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.3/lib/sinatra/base.rb:1041:in `block in invoke'
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.3/lib/sinatra/base.rb:1041:in `catch'
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.3/lib/sinatra/base.rb:1041:in `invoke'
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.3/lib/sinatra/base.rb:882:in `call!'
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.3/lib/sinatra/base.rb:870:in `call'
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/rack-protection-1.5.0/lib/rack/protection/xss_header.rb:18:in `call'
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/rack-protection-1.5.0/lib/rack/protection/path_traversal.rb:16:in `call'
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/rack-protection-1.5.0/lib/rack/protection/json_csrf.rb:18:in `call'
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/rack-protection-1.5.0/lib/rack/protection/base.rb:49:in `call'
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/rack-protection-1.5.0/lib/rack/protection/base.rb:49:in `call'
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/rack-protection-1.5.0/lib/rack/protection/frame_options.rb:31:in `call'
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/rack-1.5.2/lib/rack/nulllogger.rb:9:in `call'
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.3/lib/sinatra/showexceptions.rb:21:in `call'
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.3/lib/sinatra/base.rb:175:in `call'
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.3/lib/sinatra/base.rb:1949:in `call'
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/rack-1.5.2/lib/rack/builder.rb:138:in `call'
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/rack-1.5.2/lib/rack/urlmap.rb:65:in `block in call'
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `each'
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `call'
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/rack-1.5.2/lib/rack/lint.rb:49:in `_call'
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/rack-1.5.2/lib/rack/lint.rb:37:in `call'
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/rack-1.5.2/lib/rack/showexceptions.rb:24:in `call'
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/puma-2.5.1/lib/puma/rack_patch.rb:13:in `call'
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/rack-1.5.2/lib/rack/chunked.rb:43:in `call'
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/rack-1.5.2/lib/rack/content_length.rb:14:in `call'
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/puma-2.5.1/lib/puma/server.rb:472:in `handle_request'
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/puma-2.5.1/lib/puma/server.rb:343:in `process_client'
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/puma-2.5.1/lib/puma/server.rb:242:in `block in run'
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/puma-2.5.1/lib/puma/thread_pool.rb:92:in `call'
        /home/ec2-user/.rvm/gems/ruby-1.9.3-p551/gems/puma-2.5.1/lib/puma/thread_pool.rb:92:in `block in spawn_thread'

**Comment by cburmeister** [comment]
Is this project still maintained?

@cheesegrits Your error above looks like your `.yml` configuration might have some problems.

I am currently running into this error:

```
NoMethodError - undefined method `[]' for nil:NilClass:
	/home/ec2-user/txgh/lib/strava/l10n/github_repo.rb:21:in `transifex_project'
	/home/ec2-user/txgh/app/app.rb:66:in `block in <class:Hooks>'
```

**Comment by Afterster** [comment]
Got the same error. Looks like someone fixed it few months ago in a fork https://github.com/yoozoosato/txgh

**Comment by cburmeister** [comment]
Make sure your Github webhook is passing along the proper `content-type` header:

`x-www-form-urlencoded` not `application/json`.

**Comment by matthewjackowski** [comment]
This should be fixed in Devel with this commit (used yoozoosato fork as basis).
https://github.com/transifex/txgh/commit/b79742c1f9c5b5bafefdbcd4f1376ad36fe1c8de#diff-bcf83627d6a38b2f79bb44b1ca717732L67
