### ISSUE TITLE
Unable to push to TX while on Github the deliveries are successful

### ISSUE THREAD

**Issue by saisaiwang** [transifex/txgh#50]
Hi there,

I followed the doc to build txgh on Heroku. When I push commits with updated English files. On Github I can see the delivery was successful, but I don't see any update on TX side. Also when I submit a translation on TX, I don't get anything on GitHub. Since TX doesn't pop up any error, it's a little hard to figure out what the issue is. Any suggestion would be appreciated:)

BTW the doc was a bit outdated. The var key names listed in the doc was not consistent with what's currently in the yaml file, which caused an error earlier for Github to send commits out.

Thanks in advance,
Saisai

**Comment by matthewjackowski** [comment]
Hi @saisaiwang 
Sorry to hear that it's not working for you.  The configuration can definitely be tricky!  I've made a note about the out of date configuration in the meantime it would be helpful to understand if there are any error messages coming from Heroku.  You can do this by using the ```heroku logs``` command. https://devcenter.heroku.com/articles/logging#view-logs

**Comment by matthewjackowski** [comment]
Here is a screenshot from my Heroku test account (the token and the password fields should be filled in)

![image](https://cloud.githubusercontent.com/assets/974299/13147630/8c588010-d60e-11e5-8793-eb1b433921c6.png)

**Comment by saisaiwang** [comment]
Sorry for coming back to you late @matthewjackowski but... that works for me!! Thanks so much for helping figure this out!!

Also I have a few more questions:
1. Is it possible to hook more git repos and tx projects to one heroku app?
2. What action will trigger the delivery action from TX side? On github, it's when you submit a commit. But I tried a few times, but didn't find out the trigger on TX side. If possible, we hope we don't end up with 10+ commits for one translation delivery.

Thanks a lot!

**Comment by matthewjackowski** [comment]
@saisaiwang
1. Not yet...this is functionality we are currently planning for this year however.
2. A webhook (in Transifex) is triggered when the translation or the review of a specific language reaches 100% within a project. See here for additional details: http://docs.transifex.com/integrations/webhook/
