### ISSUE TITLE
What does file_filter refer to in tx.config?

### ISSUE THREAD

**Issue by timothyylim** [transifex/txgh#68]
Hi, great work with txgh!

I have a question:

I'm trying to set up txgh for this github repo:

https://github.com/timothyylim/h5p-greeting-card

and this transfiex project:

https://www.transifex.com/joubel/h5p-greeting-card/

Let's say I just have a single resource that I need translated called en.json. Does this tx.config make sense:

```
[main]
host = https://www.transifex.com
lang_map =

# Create one such section per resource
[h5p-greeting-card.ensjon]
file_filter = language/<lang>.json
source_file = language/en.json
source_lang = en
type = json
```

And do I place this tx.config in my txgh directory or in my github repo?

Any help would be very much appreciated.

**Comment by matthewjackowski** [comment]
@timothyylim it's important that you setup locales that match what you are using in your project (ie fr, nb, nn).  Txgh will try to automatically substitute whatever locale it gets back from Transifex.  In some cases this is not desirable (you setup a different locale than what is used by your app).  In these case you'll want to use the "lang_map" field to override that default.
A more detailed description of this file format can be found here: https://docs.transifex.com/client/client-configuration

**Comment by timothyylim** [comment]
Great, thank you.
