### ISSUE TITLE
Webhook with authentification failed

### ISSUE THREAD

**Issue by lcalvy** [transifex/txgh#69]
Hi,
Since Jan 19 11:42:53.382, Verifying a webhook (https://docs.transifex.com/integrations/webhooks) doesn't work anymore without any change on ower side.

We can't use anymore https://github.com/transifex/txgh to sync github and tx du to issue in verification in production

**Comment by matthewjackowski** [comment]
@lcalvy I don't think there has been any recent updates to the Txgh project.  Are you saying that the webhooks on Transifex side have changed?

**Comment by matthewjackowski** [comment]
The code that calculates the hash is here: https://github.com/transifex/txgh/blob/master/lib/txgh/transifex_request_auth.rb#L10

After a quick visual review, I think this is still a valid approach.

**Comment by lcalvy** [comment]
Yes but this failed in production, I'm speeking with transifex team to identify where is the issue.
They have changed something, a new param was added 'event' and it's doesnt work anymore.

**Comment by matthewjackowski** [comment]
So we handle all params here:
https://github.com/transifex/txgh/blob/master/lib/txgh/transifex_request_auth.rb#L29

Just adding a new param should not break the algorithm unless there is some specific rules around the parameter that I'm not aware of (which is entirely possible).

**Comment by alexpsi** [comment]
Hello @lcalvy and @matthewjackowski we deployed a fix on transifex's side, does the issue persist?

**Comment by joekur** [comment]
What it looks like to me is that transifex started sending JSON encoded webhooks instead of www-form encoded. Changing to `JSON.parse` here seems to have done it for me: https://github.com/transifex/txgh/blob/master/lib/txgh/transifex_request_auth.rb#L27

**Comment by alexpsi** [comment]
Yes, your solution is valid for the moment, as it is equivalent to the patch we pushed at txgh some days ago. There will be some changes in how the webhook is validated, probably next week, so we will also release a new version of TXGH that will cover both url encoded and json webhooks with the new validation scheme. Sorry for any inconvenience!

**Comment by alexpsi** [comment]
Issue should be resolved by updating to the latest version found in master.
