### ISSUE TITLE
Merge devel branch into master

### ISSUE THREAD

**Issue by chainlink** [transifex/txgh#82]
Hi there,
Is there a plan to merge the devel branch with master?

I sadly just burned a bunch of time rewriting auth to work with transifex v2 only to notice it in the devel branch when I went to submit a PR :(

**Comment by SofiaMargariti** [comment]
@chainlink I am sorry you had to waste time on this, it was an oversight on my part. I've just merged devel into master so that we avoid similar issues in the future.

**Comment by chainlink** [comment]
Thanks so much!
