### ISSUE TITLE
support for multiple repos

### ISSUE THREAD

**Issue by jdoconnor** [transifex/txgh#9]
I'm not sure if this is worthwhile, but having multiple repos that can be configured for a single instance of txgh (each repo would be mapped to a transifex project) would enable a larger organization to not have to run multiple instances of the txgh bridge.

**Comment by cheesegrits** [comment]
This should be resolved with the my PR https://github.com/transifex/txgh/pull/16

**Comment by matthewjackowski** [comment]
I am trying to get some solid tests in place before I push devel->master to check these cases and close these issues.

**Comment by matthewjackowski** [comment]
master has been updated...closing
